In [1]:
import cv2
from sklearn.utils import resample
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
model = load_model('amena.h5')
#labels = ["A", "B", "C"]
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, image = cap.read()
    image = cv2.flip(image, 1)
    
    roi = image[0 : 205, 390 : 627]
    cv2.rectangle(image,pt1=(400,0), pt2=(620,200), color=(255,0,0), thickness=2)
    gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)

    Gaussain_blur = cv2.GaussianBlur(gray, (5, 5), 4)
    #cv2.imshow('Gaussain_blur',Gaussain_blur)
    th3 = cv2.adaptiveThreshold(Gaussain_blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 2)
    ret, res = cv2.threshold(th3, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    #kernel = np.ones((3, 3), np.uint8)
    #closing = cv2.morphologyEx(res, cv2.MORPH_CLOSE, kernel, iterations=1)
    test_image = res / 255
    test_images = cv2.resize(test_image, (224, 224), 1)
    test_images = np.expand_dims(test_images, 0)
    pred_img = model.predict(np.array(test_images))
    print(pred_img)
    pred_result = np.argmax(pred_img, axis=1)
    #print(pred_result)
    
    if pred_result==0:
        preds="A"
    elif pred_result==1:
        preds="B"
    else:
        preds="C"
    print(preds)
    cv2.putText(image,preds,(75,50),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)
    cv2.imshow("image",image)
    if cv2.waitKey(20) & 0xFF == ("q"):
        break

cv2.destroyAllWindows()
cap.release()

[[0.926277   0.01416869 0.05955432]]
A
[[0.9289464  0.01402088 0.05703267]]
A
[[0.9235205  0.015187   0.06129257]]
A
[[0.9286967  0.0138784  0.05742486]]
A
[[0.9310864  0.01397    0.05494362]]
A
[[0.93173593 0.01371231 0.05455173]]
A
[[0.9276548  0.01372131 0.05862385]]
A
[[0.9283272  0.01362799 0.05804483]]
A
[[0.92723745 0.01436205 0.0584005 ]]
A
[[0.9260565  0.01373344 0.06021003]]
A
[[0.929336   0.01335852 0.05730545]]
A
[[0.92676985 0.01393084 0.05929939]]
A
[[0.9289254  0.01352686 0.05754764]]
A
[[0.92853343 0.01359855 0.05786793]]
A
[[0.9306031  0.01353306 0.05586389]]
A
[[0.92756987 0.01373452 0.0586956 ]]
A
[[0.9278131  0.01369532 0.05849158]]
A
[[0.928285   0.01361937 0.05809563]]
A
[[0.93326557 0.01378536 0.05294906]]
A
[[0.9275485  0.0140239  0.05842751]]
A
[[0.9294758  0.01345859 0.05706564]]
A
[[0.92956156 0.01340381 0.05703457]]
A
[[0.92903423 0.01334198 0.05762378]]
A
[[0.9305231  0.0133442  0.05613267]]
A
[[0.9279921  0.01416801 0.0578399 ]]
A
[[0.9314459  0.01312557 0

KeyboardInterrupt: 